crosscloudci/ci-dashboard

src/App.vue
src/lib/demo-data.json

problem:
- footer overlaps the last project row (ONAP)
cause:
- new project, Envoy, was added
resolved by: 
- increase mq by 80 px

update mq for footer on staging

---

src/App.vue
src/lib/demo-data.json

increase media area by 80 px to allow for new project row, Envoy

updating the mq for the footer on cidev

---

src/components/AppFooter.vue

- update url for github icon
- update url for bug icon
- update email to cncfci@

#125 update urls for icons in footer

---

src/components/TestEnvironment.vue

- update url for github icon
- update url for bug icon
- update email address

#125 update url for github/report bug icons

---

Gemfile.lock
README.md
src/components/TestEnvironment.vue

* fixed last updated bug 
* fixed ruby gem vulnerability issues

Merge last updated bug and vulnerability issues 

---

src/components/TestEnvironment.vue

crosscloudci/ci-dashboard#77
Changes made:

#77 replace K8s png logo with svg logo

---

src/components/PageHeader.vue

https://github.com/crosscloudci/ci-dashboard/issues/77
Changes made:

#77 replace CNCF png logo with svg logo in header

---

src/components/PageHeader.vue

#77 remove single quote from svg logo in header

---

src/components/PageHeader.vue

https://github.com/crosscloudci/crosscloudci/issues/139
- add : after "Last updated"

update "Last updated:" label

---

src/assets/images/pipe-gfx.svg
src/assets/stylesheets/_main-table.scss
src/components/PageHeader.vue
src/components/TestEnvironment.vue

updated frontend to handle dynamic test environment options for K8's 
This PR is dependent on the status repository changes.  It should be promoted at the same time.
-  [x] Promote https://github.com/crosscloudci/ci_status_repository/pull/18 then promote #86 
crosscloudci/crosscloudci#114

Add K8s environment selection via drop-down

---

src/components/MainTable.vue
src/components/TestEnvironment.vue
src/store/actions.js
src/store/modules/test_environments.js

Added support for choosing between environments on the cncf.ci dashboard 
dependency: 
https://github.com/crosscloudci/ci_status_repository

Enable Arm64 support in TestEnvironment for K8s

---

src/components/TestEnvironment.vue

crosscloudci/ci-dashboard#90
Changes made: add /projects/ to URL
Line 7:            ``` <img :src="'https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg?sanitize=true'" />```
Line 27: ```            <img :src="'https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg?sanitize=true'"```

update K8s logo w/ project directory URL

---

src/components/PageHeader.vue

crosscloudci/ci-dashboard#90
Changes made: add /projects/ to URL

update CNCF logo w/ project directory URL

---

src/App.vue
src/assets/stylesheets/_mixins.scss
src/components/AppFooter.vue
src/components/TestEnvironment.vue

#188 Update label, checkmarks, and hover styling on dropdown.
#156 Updates to footer styling.

Update styling of test environment dropdown. 

---

Dockerfile
build/webpack.prod.conf.js
entrypoint.sh

updated docker and webpack build config to deploy vuejs in production mode instead of dev

Docker Production config

---

Dockerfile
entrypoint.sh

$NODE_PORT was not being seen by serve cli for serving static frontend vuejs app. Built Docker container successfully runs on dev box.

updated deploy code to successfully start static server

---

src/components/TestEnvironment.vue
src/store/modules/projects.js
src/store/modules/session.js
src/store/modules/test_environments.js

fixes: https://github.com/crosscloudci/crosscloudci/issues/186

Radio buttons

---

Dockerfile
README.md
package.json

refs: https://github.com/crosscloudci/crosscloudci/issues/171

update to node 10 lts. also some readme updates

---

Dockerfile
README.md
package.json
src/components/TestEnvironment.vue
src/store/modules/test_environments.js

Explicitly sorting order of TestEnvironment component's radio buttons

Radio Button Order

---

src/components/TestEnvironment.vue

re: https://github.com/crosscloudci/crosscloudci/issues/211
http://dev.jeffersonscher.com/resolution.html

fix for test env text

---

src/App.vue
src/components/TestEnvironment.vue

1. Fixes Footer UI on all supported desktop browsers 
Issues:
- basically any issue where a new project is added would have cause the issue this pr is to fix
- crosscloudci/crosscloudci#35

Promote Footer UI fix to production

---

package-lock.json
package.json

hotfix kinf of

---

package-lock.json
package.json

https://github.com/vulk/cncf_ci/issues/357

hotfix for hpa

---

.gitlab-ci.yml

Need to remove the --force flag on deploy as it was error with spec.ClusterIP invalid value "" immutable error.

Fixes immutable error on deploys - Remove --force flag
